Feature/header sidebar
belgamo/comarev-dashboard pull request #12
Opened 2021-06-29 23:01 UTC by m-pereira

### Overview

* add styles to dashboard page
* handle forbidden users

### Screeshots

as normal user:
![image](https://user-images.githubusercontent.com/47258878/123877979-9bb78100-d914-11eb-9ac7-61b3b6f09b73.png)
as admin user:
![image](https://user-images.githubusercontent.com/47258878/123878070-c275b780-d914-11eb-9906-5959dc2cecb8.png)

2021-06-29 23:18 UTC, belgamo requested changes

2021-06-29 23:18 UTC, belgamo commented on package.json
> +    "toastify": "^2.0.1",
Why do you need two toastify libs?

2021-06-29 23:18 UTC, belgamo commented on src/pages/dashboard/dashboard.component.js
> +          .filter((item) => user.admin || !item.admin)
Missing tests.

2021-06-29 23:18 UTC, belgamo commented on src/pages/dashboard/dashboard.hooks.js
> +  const handleSignOut = () => {
What do you think to abstract it to another hook like `useAuthorization` so that you can share the auth helpers throughout the whole application?

2021-06-29 23:18 UTC, belgamo commented on src/pages/list-user/list-user.component.js
> +// import { Container } from './styles';
Remove comment.

2021-06-29 23:18 UTC, belgamo commented on src/routes/secure-route.component.js
> +const SecureRoute = ({ component: Component, admin, ...rest }) => {
Missing tests.

2021-06-29 23:28 UTC, m-pereira commented on src/pages/dashboard/dashboard.component.js
> +          .filter((item) => user.admin || !item.admin)
thanks

2021-06-29 23:28 UTC, m-pereira commented on package.json
> +    "toastify": "^2.0.1",
thanks!

2021-09-23 22:30 UTC, belgamo commented on src/routes/secure-route.component.js
> +const SecureRoute = ({ component: Component, admin, ...rest }) => {
Let's do this test in another PR, it's quite complicated.

2021-09-23 22:30 UTC, belgamo commented on src/pages/dashboard/dashboard.hooks.js
> +  const handleSignOut = () => {
Let's do this in another PR.

2021-09-23 22:31 UTC, belgamo approved these changes

2021-09-23 22:31 UTC, merged